#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the current branch name
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Run lint-staged for all branches
npx lint-staged

# Run tests if we're on the main branch
if [ "$BRANCH_NAME" = "main" ]; then
  echo "Running tests before commit on main branch..."
  npm test
fi 